### PR TITLE
Test against Ruby 2.7 in CI

### PR DESCRIPTION
**Pull request by okuramasafumi**

### CODE REVIEW

**Comment by okuramasafumi** [comment]
Hmm, `bundle install` command fails with Ruby 2.7 but in my local environment it works.
Is it a problem of rvm?

**Comment by okuramasafumi** [comment]
@amatsuda Sorry for the delay, I changed the Ruby version from `2.7.0` to `2.7.1` and the CI passed (maybe Travis resolved something?)

**Comment by amatsuda** [comment]
@okuramasafumi 
> maybe Travis resolved something?

Nah. Please read the commits history and see what we did ;)

**Comment by okuramasafumi** [comment]
I guess what you mentioned is this one: https://github.com/amatsuda/database_rewinder/commit/dac2687aed0068bbd71e7b2c8229cb504420e753

Now I see this workaround resolves broken CI, although it's a bit annoying to add it to many gems.
Anyway, thank you!

**Pull request merged**
